/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    BarChart: typeof import('./src/components/cards/BarChart.vue')['default']
    copy: typeof import('./src/components/cards/Table copy.vue')['default']
    CreateIssue: typeof import('./src/components/CreateIssue.vue')['default']
    DADVueNext: typeof import('./src/components/DADVueNext.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DonutChart: typeof import('./src/components/cards/DonutChart.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    FloatingActionButtons: typeof import('./src/components/FloatingActionButtons.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Groups: typeof import('./src/components/cards/Groups.vue')['default']
    GroupsCard: typeof import('./src/components/GroupsCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'ITabler:versionsFilled': typeof import('~icons/tabler/versions-filled')['default']
    ITablerArrowsMaximize: typeof import('~icons/tabler/arrows-maximize')['default']
    ITablerArrowsMinimize: typeof import('~icons/tabler/arrows-minimize')['default']
    ITablerArrowUp: typeof import('~icons/tabler/arrow-up')['default']
    ITablerCircleDashedLetterX: typeof import('~icons/tabler/circle-dashed-letter-x')['default']
    ITablerCircleLetterX: typeof import('~icons/tabler/circle-letter-x')['default']
    ITablerClockEdit: typeof import('~icons/tabler/clock-edit')['default']
    ITablerInfoCircleFilled: typeof import('~icons/tabler/info-circle-filled')['default']
    ITablerMessageReport: typeof import('~icons/tabler/message-report')['default']
    License: typeof import('./src/components/License.vue')['default']
    LineChart: typeof import('./src/components/cards/LineChart.vue')['default']
    Medias: typeof import('./src/components/cards/Medias.vue')['default']
    Members: typeof import('./src/components/cards/Members.vue')['default']
    Membership: typeof import('./src/components/cards/Membership.vue')['default']
    Pages: typeof import('./src/components/cards/Pages.vue')['default']
    PagesBackup: typeof import('./src/components/cards/Pages-backup.vue')['default']
    Table: typeof import('./src/components/cards/Table.vue')['default']
    TotalGroups: typeof import('./src/components/cards/TotalGroups.vue')['default']
    TotalMedias: typeof import('./src/components/cards/TotalMedias.vue')['default']
    TotalMembers: typeof import('./src/components/cards/TotalMembers.vue')['default']
    TotalPages: typeof import('./src/components/cards/TotalPages.vue')['default']
    TotalUsers: typeof import('./src/components/cards/TotalUsers.vue')['default']
    Tour: typeof import('./src/components/Tour.vue')['default']
    UserActivity: typeof import('./src/components/cards/UserActivity.vue')['default']
  }
}
